# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  server:
    build:
      context: server
      dockerfile: server.Dockerfile
    ports:
      - "127.0.0.1:${NOMAD_PORT:-4646}:4646"

  client:
    depends_on:
      - server
    build:
      context: client
      dockerfile: client.Dockerfile
    # nomad clients run as root, but they create cgroups to do their dirty work
    # so we need to give the container permission to do that stuff
    cgroup: host
    privileged: true
